apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
spec:
  replicas: 2  # Pod を 2 つ作成
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          #image: ghcr.io/hotogayato/spring/myapp:latest  # Docker Hub から取得
          image: ghcr.io/tkhs-work/myapp:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: spring
  ports:
    - protocol: TCP
      port: 80        # Service 内部のポート
      targetPort: 80  # Pod のコンテナポート
      nodePort: 30080 # 外部アクセス用のポート
  type: NodePort  # 外部アクセスを許可
